# https://githooks.com/
# https://verdantfox.com/blog/how-to-use-git-pre-commit-hooks-the-hard-way-and-the-easy-way
# https://docs.astral.sh/ruff/integrations/
# https://pre-commit.com/

# Commands:
#   pre-commit run  # Запустить pre-commit проверку для теста
#   pre-commit install  # Создать файл в директории .git/hooks/pre-commit

# После создания файла, при любом git commit будет запускаться pre-commit проверка.

# Если возникли проблемы с pre-commit и нужно срочно сделать commit то можно
# временно удалить проверку до выяснения проблемы с помощью:
#   pre-commit uninstall

# Либо можно воспользоваться флагом при коммите (--no-verify или -n):
# git commit --no-verify -m "msg"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.4.1'
    hooks:
      - id: ruff
        name: Проверка кода ruff линтером.
        args: [
          --fix,
          --quiet,
          # --silent,
        ]

      - id: ruff-format
        name: Проверка кода ruff форматтером.
